### ISSUE TITLE
Differences between sum and totals

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#33]
Right now I am comparing some numbers and ran into an effect I can't explain myself.
I try to strip this report from confidential bits, so I am sorry if I can't provide too much details.

This is the request I make, to get the breakdown for an „overtime” report which involves a Calculated Metric:
```
{
    "reportDescription": {
        "reportSuiteID": "my_report_suite_id",
        "dateFrom": "2018-10-01",
        "dateTo": "2018-10-31",
        "dateGranularity": "day",
        "metrics": [
            {
                "id": "cm1234_somehash"
            }
        ],
        "elements": null,
        "segments": [],
        "locale": "en_US",
        "currentData": false,
        "anomalyDetection": false,
        "expedite": false,
        "elementDataEncoding": "base64"
    }
}
```

Now, when I make a second request, but without `"dateGranularity": "day"` the response contains the totals of that month.
However, the sum is different from the totals of a month.

Since I can't reproduce it with „normal” metrics, I suspect the Calculated Metric is too blame here (I likely can't share its definition with you).
My expectation would be that Adobe Analytics would be able to sum up numbers, so the totals would match it.

Is my issue understandable? If not, what further information do you need?

**Comment by gigazelle** [comment]
Hi @Ryuno-Ki, this is a common issue that happens when you sum line items that are typically aggregated in reporting. For example, your site had 21 visits over the last two days. Your report says that 10 visits happened yesterday, and 12 visits the day before. The reason why these don't add up is because one of those visits spanned across midnight. Since that visit spanned midnight, it is counted in both days, but the total number of visits remains accurate.

I suspect that your calculated metric is showing similar behavior. It is most common with metrics that persist or otherwise can attribute to more than one line item. Feel free to reopen this if you can provide more info on the specific call that is producing unexpected results. Thanks!
