### ISSUE TITLE
Swagger authorizations

### ISSUE THREAD

**Issue by alcazes** [AdobeDocs/analytics-1.4-apis#35]
I wanted to use https://adobedocs.github.io/analytics-1.4-apis/swagger-docs.html# but it keeps failing when I authenticate

What is the correct redirection URI?
I used: 

- https://ims-na1.adobelogin.com/ims/token/v1
- https://authorize.omniture.com/authorize
- https://marketing.adobe.com/authorize

without success. I get this error each time: 
`ERROR The redirect URI provided is missing or does not match`

I created a Legacy OAuth Applications with type `implicit`

Does it need to be an integration using Adobe I/O ?

**Comment by stevja1** [comment]
Hi -

That swagger endpoint is for our older version of the Analytics API (1.4). The swagger page doesn't authenticate for you because the 1.4 API uses a non-standard authentication method. The swagger page is intended as documentation only and not a functional API client.

There are good instructions here for using Postman to authenticate and try out the API:
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/postman

Detailed information about authentication, with code examples is available here:
https://github.com/AdobeDocs/analytics-1.4-apis/tree/master/wsse

While the 1.4 API does support OAuth, it can be a pain to get it setup correctly. Furthermore, a newer version of the API is available (2.0) and is properly exposed through Adobe I/O. Its [swagger page](https://adobedocs.github.io/analytics-2.0-apis/) _is a functional client_ and is more inline with what you'd expect from a modern API. I suggest you check it out. It currently doesn't support JWT OAuth, but that feature is coming very soon.

More info is available here:
https://www.adobe.io/apis/experiencecloud/analytics/docs.html

I hope this helps!
Jared
