### ISSUE TITLE
Report.Get returns partial data for Data Warehouse reports

### ISSUE THREAD

**Issue by tonypapousek** [AdobeDocs/analytics-1.4-apis#36]
When using `Report.Queue` to request a warehouse source report, the corresponding `Report.Get` response only includes part of the data.

For example, when requesting from 10/28 to 11/25, only data to 11/6 appears.
The response from Report.Get indicates a longer period ( `"period": "2018-10-28T00:00:00-0700/2018-11-25T00:00:00-0800"`).

Also included in the response is:

```json
"page": 1,
"totalPages": 3
```
This leads me to believe the rest of the data is in pages 2 and 3 can be called via a similar method, but I can't find the relevant documentation.

What's the recommended way of doing this?

**Comment by garyr** [comment]
Hey @tonypapousek - It seems the optional `page` request parameter is missing from the `Report.Get` method documentation. You can include the `page` parameter in the request body or query string of the call to `Report.Get`. The default value is `1` and the range can be `1` to the value `totalPages`. Feel free to submit a PR to adjust the documentation. Otherwise, we'll add it to our list of things to do

**Comment by tonypapousek** [comment]
Hey @garyr 

When using the `page` parameter in the body, I don't always get the correct page (i.e. a request for page 2 returns page 3). This is particularly problematic when looping through the remaining pages and not seeing all data come back.

**Comment by tonypapousek** [comment]
@garyr 

This should be resolved by pull request #41. Please let me know if I can provide any additional documentation or examples.

**Comment by stevja1** [comment]
Closing
