### ISSUE TITLE
ReportSuite.GetMarketingChannelRules - Missing eVar #

### ISSUE THREAD

**Issue by klcodanr** [AdobeDocs/analytics-1.4-apis#65]
The ReportSuite.GetMarketingChannelRules method returns an array of the rules, however for eVar based rules it fails to return the actual eVar ID in question.

Example Response for a rule referencing eVar72 (id's are just sample numbers):

```{
 

   "ruleset_id": 345,

   "channel_id": 1,

   "junction": "all",

   "channel_value": {

   "type": "referring_domain",

   "id": "0",

   "query_string_parameter": ""

  },

   "rules": [

  {

   "rule_id": 123,

   "hit_attribute": {

   "type": "evar",

   "query_string_parameter": ""

  },

   "operator": "equals",

   "matches": [

   "12312313"

  ]

  }```

**Comment by ridmaur** [comment]
Better late than never:

This is by design. It return the **type**: which is eVar, not the specific eVar. The API spec details that type can be an enum with values: campaign, evar, referring_domain, referring_url, referring_qs_param, page, page_url, page_qs_param, search_engine, search_keywords, search_tracking_code, search_center, referring_root_domain, referring_domain_and_path, page_domain, page_root_domain, page_domain_and_path.
