### ISSUE TITLE
Missing Method ReportSuite.GetProcessingRules

### ISSUE THREAD

**Issue by klcodanr** [AdobeDocs/analytics-1.4-apis#66]
I see #7 mentions that processing rules are not supported via the API, but is there a good reason? I could see why one might not want to _create_ processing rules via the API, but why not allow API users to see that they exist?

**Comment by nateprice7** [comment]
I think that there are some concerns around letting users create and change processing rules via the API since making the wrong change in this area can cause a number of problems. We will need to put a lot of planning and thought into that functionality before we can add it to the APIs. I think that your right that there isn't the same concern around being able to read processing rules though. It's not likely that we would add that feature to the 1.4 API since most of our new development efforts are going into the newer 2.0 APIs (https://github.com/AdobeDocs/analytics-2.0-apis). If you want to put an issue against the 2.0 APIs we can consider it on our future roadmap.

**Comment by JMiller-Disco** [comment]
Please see the following requests for the 2.0 API, since this is a very desirable feature:
- [EC League Idea](https://experienceleaguecommunities.adobe.com/t5/adobe-analytics-ideas/access-processing-rules-via-api/idi-p/340186/highlight/true)
- [EC League Question](https://experienceleaguecommunities.adobe.com/t5/adobe-analytics-questions/missing-analytics-v2-0-api/qaq-p/362599/comment-id/18787#M18787)
