### ISSUE TITLE
No mention of Mobile SDKs

### ISSUE THREAD

**Issue by michaelwexler** [AdobeDocs/analytics-1.4-apis#9]
https://marketing.adobe.com/developer sends users here to learn more about Mobile SDKs.  Easy solution is to include link to https://github.com/Adobe-Marketing-Cloud/mobile-services/releases in the front page/readme; could also include a link to https://marketing.adobe.com/resources/help/en_US/mobile/ios/ and https://marketing.adobe.com/resources/help/en_US/mobile/android/ just to save folks the trouble.

**Comment by stevja1** [comment]
Hello --

We're actually shuttering the marketing.adobe.com/developer site. It will be gone in September. We're moving everything to GitHub so that we can accept PRs for documentation, SDKs, etc.

With that in mind -- I'd love your feedback on where we could document the location for the SDK and documentation on GitHub.

Thanks,
Jared
